#!/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP-1 -d I II III IV V
bspc monitor HDMI-1 -d VI VII VIII IX X 

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true


# Colors are in the form #RRGGBB, booleans are true, on, false or off.
# Color of the border of an unfocused window.
bspc config normal_border_color '#249EA0'

# Color of the border of a focused window of an unfocused monitor.
bspc config active_border_color '#FF8A25'


# Color of the border of a focused window of a focused monitor.
bspc config ocused_border_color '#005F60'
#
# Color of the node --presel-{dir,ratio} message feedback area.
bspc config resel_feedback_color '#2081F9'


bspc rule -a neovide desktop='^2' state=pseudo_tiled rectangle=1366x768+0+0 follow=on
bspc rule -a Vifm state=pseudo_tiled follow=on
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium state=floating follow=on
##bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a $HOME/.config/bspwm/programs/rofiShowSystemFonts state=pseudo_tilted rectangle=1366x768+0+0 follow=on
